### ISSUE TITLE
OS unsupported:  ERROR: No 'C' compiler found to build 'threads'

### ISSUE THREAD

**Issue by isgilman** [rurban/threads#1]
Hello, I've been trying to install `threads` with `cpanm` for a little while now and can't figure out the following error:

```bash
/home/isg4/.cpanm/work/1556545965.28549/build.log
cpanm (App::cpanminus) 1.7044 on perl 5.026002 built for x86_64-linux-thread-multi
Work directory is /home/isg4/.cpanm/work/1556545965.28549
You have make /usr/bin/make
You have LWP 6.36
You have /usr/bin/tar: tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching threads () on cpanmetadb ...
--> Working on threads
Fetching http://www.cpan.org/authors/id/J/JD/JDHEDDEN/threads-2.21.tar.gz
-> OK
Unpacking threads-2.21.tar.gz
Entering threads-2.21
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.34)
Configuring threads-2.21
Running Makefile.PL
OS unsupported:  ERROR: No 'C' compiler found to build 'threads'
-> N/A
-> FAIL Configure failed for threads-2.21. See /home/isg4/.cpanm/work/1556545965.28549/build.log for details.
Expiring 15 work directories.
```

I'm no perl expert, but I've checked all of the perl and compiler related things I can think of and everything checks out, plus I successfully installed multiple modules using `cpanm` directly before getting stuck on `threads`. The remote server I'm working on also has Development Tools installed.

```bash
(funannotate) [isg4@farnam2 envs]$ which perl cpan cpanm cc gcc g++ make cmake
/gpfs/ysm/home/isg4/.ycrc/envs/funannotate/bin/perl
/gpfs/ysm/home/isg4/.ycrc/envs/funannotate/bin/cpan
/gpfs/ysm/home/isg4/.ycrc/envs/funannotate/bin/cpanm
/ysm-gpfs/home/isg4/.linuxbrew/bin/cc
/ysm-gpfs/home/isg4/.linuxbrew/bin/gcc
/ysm-gpfs/home/isg4/.linuxbrew/bin/g++
/usr/bin/make
/usr/bin/cmake
```

I'm working within a `conda` environment and checking `conda list` I have

```
libgcc                    7.2.0                h69d50b8_2
libgcc-ng                 8.2.0                hdf63c60_1
perl-cpan-meta            2.150010                pl526_0    bioconda
perl-cpan-meta-requirements 2.140                   pl526_0    bioconda
perl-cpan-meta-yaml       0.018                   pl526_0    bioconda
```

 Any help would be much appreciated!

Thanks, 
Ian

**Comment by rurban** [comment]
>  Working on threads
> Fetching http://www.cpan.org/authors/id/J/JD/JDHEDDEN/threads-2.21.tar.gz
> -

This means you are building the official threads package by Jeremy Hedden, the maintainer.
This repo here is only for cperl fixes. You need to ask upstream: 
https://metacpan.org/pod/threads

> OS unsupported:  ERROR: No 
> 'C' compiler found to build ‘threads'

This means the C compiler which was used to build is missing.
Check `perl -V:cc` and install it.
If it’s a cross-compilation target, cpan and ExtUtils::MakeMaker do not support cross-compilation.
You really need to build your modules with a cross-compiled perl then.
